# Generated by Django 2.2.7 on 2019-11-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='home.jpg', upload_to='')),
                ('area', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
    ]
