# Generated by Django 2.2.7 on 2019-11-24 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('Sale', 'sale'), ('Rent', 'rent')], default='Sale', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='garage',
            field=models.IntegerField(default=1),
        ),
    ]
