# Generated by Django 2.2.7 on 2019-11-25 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191124_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='image',
            new_name='main_photo',
        ),
        migrations.AddField(
            model_name='property',
            name='listing_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(choices=[('KR', 'Karen'), ('MT', 'Muthaiga'), ('RN', 'Runda'), ('GE', 'Garden_Estate'), ('RU', 'Ruiru')], default='KR', max_length=3),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_1',
            field=models.ImageField(default='home.jpg', upload_to='Property'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_2',
            field=models.ImageField(default='home.jpg', upload_to='Property'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_3',
            field=models.ImageField(default='home.jpg', upload_to='Property'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_4',
            field=models.ImageField(default='home.jpg', upload_to='Property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('SL', 'Sale'), ('RE', 'Rent')], default='SL', max_length=10),
        ),
    ]
