# Generated by Django 2.2.7 on 2019-11-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_property_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(choices=[('Karen', 'KR'), ('Muthaiga', 'MT'), ('Runda', 'RN'), ('Garden_Estate', 'GE'), ('Ruiru', 'RU')], default='Karen', max_length=3),
        ),
    ]
