# Generated by Django 3.0rc1 on 2019-12-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191128_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(choices=[('KR', 'Karen'), ('MT', 'Muthaiga'), ('RN', 'Runda'), ('GE', 'Garden_Estate'), ('RU', 'Ruiru')], default='KR', max_length=20),
        ),
    ]
