# Generated by Django 3.0rc1 on 2019-12-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191201_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo_1',
            field=models.ImageField(default='home.jpg', upload_to='Property/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_2',
            field=models.ImageField(default='home.jpg', upload_to='Property/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_3',
            field=models.ImageField(default='home.jpg', upload_to='Property/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_4',
            field=models.ImageField(default='home.jpg', upload_to='Property/%Y/%m/%d'),
        ),
    ]
