# Generated by Django 3.0rc1 on 2019-12-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191201_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.ImageField(default='default.jpeg', upload_to='Agents/%Y/%m/%d'),
        ),
    ]
