# Generated by Django 3.0 on 2020-02-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191201_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
            ],
        ),
    ]
