# Generated by Django 3.0 on 2020-02-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200221_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.ImageField(upload_to='Agents/%Y/%m/%d'),
        ),
    ]
