# Generated by Django 3.0 on 2020-02-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200221_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Agents/%Y/%m/%d'),
        ),
    ]
