# Generated by Django 3.0 on 2020-02-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='main_photo',
            field=models.ImageField(default='blackroq_3.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_1',
            field=models.ImageField(upload_to='Property/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_2',
            field=models.ImageField(upload_to='Property/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_3',
            field=models.ImageField(upload_to='Property/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_4',
            field=models.ImageField(upload_to='Property/%Y/%m/%d'),
        ),
    ]
