# Generated by Django 3.0 on 2020-04-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200229_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(default='MALINDI', max_length=50),
        ),
    ]
