# Generated by Django 3.0 on 2021-06-01 11:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200403_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_photo',
            field=cloudinary.models.CloudinaryField(default='blackroq_3.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='photo_1'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_2',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='photo_2'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_3',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='photo_3'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_4',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='photo_4'),
        ),
    ]
