# Generated by Django 3.0 on 2021-06-01 11:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210601_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='photo_2'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='photo_3'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='photo_4'),
        ),
    ]
