# Generated by Django 3.0 on 2020-02-20 13:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(default='Body:'),
            preserve_default=False,
        ),
    ]
