# Generated by Django 3.0 on 2020-02-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='post.jpeg', upload_to='Post %Y%M%d'),
        ),
    ]
